---
exclude_paths:
  - 'staircase/_version.py'
  - 'staircase/_typing.py'
  - 'staircase/__init__.py'
  - 'tests/**/*'
  - 'tests/*'
  - 'benchmarks/**/*'
  - 'setup.py'
  - 'versioneer.py'
  - 'README.md'
  - 'docs/*'
  - 'docs/**/*'
  - '.github/*'
